### ISSUE TITLE
Error when using recon-neonatal-cortex

### ISSUE THREAD

**Issue by Thea-Eddie-Amy** [BioMedIA/MIRTK#761]
Hi,
I was trying to use the `MIRTK recon-neonatal-cortex`, I run the command like this:
`mirtk recon-neonatal-cortex -v --threads=4 --config=C:\Users\lenovoM425\Desktop\dHCP_pipeline_test\dhcp-structural-pipeline-master\parameters\recon-neonatal-cortex.cfg --session=test-0 --prefix=surfaces\test-0\vtk\test-0 --temp=surfaces\test-0\vtk\temp-recon\test-0 --white --pial`

however gets the error
`Reconstructing cortical surfaces of test session 0
Dividing brain volume into disjoint regions

Traceback (most recent call last):
  File "C:\Users\lenovoM425\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 789, in get
    value = d[option]
  File "C:\Users\lenovoM425\AppData\Local\Programs\Python\Python38\lib\collections\__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\Users\lenovoM425\AppData\Local\Programs\Python\Python38\lib\collections\__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'fill_wm_holes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\CMake Program Files\MIRTK\Lib\Tools\recon-neonatal-cortex.cmd", line 923, in <module>
    recon_neonatal_cortex(config=config, section=args.section, config_vars=config_vars,
  File "D:\CMake Program Files\MIRTK\Lib\Tools\recon-neonatal-cortex.cmd", line 480, in recon_neonatal_cortex
    require_brain_mask(config, section, config_vars, stack, verbose,
  File "D:\CMake Program Files\MIRTK\Lib\Tools\recon-neonatal-cortex.cmd", line 228, in require_brain_mask
    require_regions_mask(config, section, config_vars, stack, verbose)
  File "D:\CMake Program Files\MIRTK\Lib\Tools\recon-neonatal-cortex.cmd", line 207, in require_regions_mask
    fill_wm_holes=config.getboolean(section, 'fill_wm_holes'),
  File "C:\Users\lenovoM425\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 828, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
  File "C:\Users\lenovoM425\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "C:\Users\lenovoM425\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "C:\Users\lenovoM425\AppData\Local\Programs\Python\Python38\lib\configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'fill_wm_holes' in section: 'recon-neonatal-cortex'`

Please help, thanks.

**Comment by schuhschuh** [comment]
Hi, you will see this error with an "older" version of MIRTK. I've added the `fill_wm_holes` option only in recent months. To use it, you have to use the latest HEAD revision of the master branch. Please note that due to a bug in VTK <9, you have to build MIRTK with VTK 9. This unfortunately affects the AppImage that is available on bintray. I should have submitted a fix for this by the end of this week.

Otherwise, if you want to keep using the MIRTK version you have, you will have to remove the new option from your input configuration file.
